service: aws-two-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2 
  ecr:
    images:
      appimage:
        path: ./
  timeout: 110
  memorySize: 3008
functions:
  app:
    image:
      name: appimage
    events:
      - httpApi: '*'

# plugins:
#   - serverless-wsgi
#   - serverless-python-requirements
